# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b25844b3298a3e2b63c1383ec410a47b51eeee8f07b88aee9d1f1d4fa07c9288924377fcb59c638edc28e9436b47c3980863ae0ff02b600c794abb8d77420d0

test:
  secret_key_base: 204347d668d73a44ea237450293aa28195fe6ef3b5026c019498248fdc160942acd42be3a59f21fec2e739b5d7bd8a9b4fbc03eaade68bdcbb7d5f55bbf50d79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
